[package]
name = "onebrc"
version = "0.1.0"
edition = "2021"


[[bin]]
name="slow"
path="./src/slow_main.rs"

[[bin]]
name="fast"
path="./src/fast_main.rs"


[profile.release]
debug = true
codegen-units=1
lto=false

[dependencies]
memchr = "2.7.4"
rustc-hash = "2.0.0"

